config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'sessions#index'
  delete 'sign_out', to: 'sessions#destroy'
  get 'sign_in', to: 'sessions#new'
  root 'sessions#index'

  resources :sessions, only: [:new, :create]
  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts

  validates :email, uniqueness: true
  validates_format_of :email, with: /@/, message: "is invalid"
  validates :password, length: { minimum: 4, message: "is too short (minimum is 4 characters)"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_logged_in

  def current_user
  @c_user ||= User.find( session[:user_id] ) if session[:user_id]
  end
  # if !@c_user.blank?
  #   return @c_user
  # end
  # if session[:user_id]
  #   @c_user = User.find(session[:user_id])
  # end

  def user_logged_in?
    current_user.present?
  end

  def authenticate_user
    unless user_logged_in?
      flash[:notice] = "You must log in to access this page."
      redirect_to home_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]
  before_action :your_post?, except: [:index, :show, :new, :create]

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to [current_user, @post], notice: "successfully created"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to user_post_path(current_user, @post), notice: "successfully updated"
    else
      render "edit", notice: "Not successful!"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_posts_path(session[:user_id]), notice: "successfully destroyed"
  end

private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def your_post?
    # incomplete - need to compare to user_id from url.
      @post = Post.find(params[:id])
     redirect_to home_path, notice: "This post doesn't belong to you!" unless @post.user == current_user

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @username = User.find_by(id: session[:user_id])
    @post = Post.all.order(created_at: :desc)
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "Login was successful!"
    else
      flash[:notice] = "Couldn't sign you in. Please check your email and password."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to home_path, notice: "Welcome"
    else
      render "new", notice: "Sign up failed! Please contact administrator."
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<%= form_for [current_user, @post] do |p| %>
  <%= p.label :title %> <br>
  <%= p.text_field :title %>
  <br>
  <%= p.label :body %> <br>
  <%= p.text_area :body %>
  <br>
  <%= p.submit "Update Post" %>
<% end %>

<%= link_to "Back", user_posts_path %>

app/views/posts/index.html.erb
<h1> All My Posts </h1>

<% @post.each do |p| %>
<%= p.title %> <br>
<%= p.body %>
<%= link_to "Show", user_post_path(current_user, p) %>
<%= link_to "Destroy", user_post_path(current_user, p), method: :delete %>
<%= link_to "Edit", edit_user_post_path(current_user, p) %>
<hr>

<% end %>

<%= link_to "Home", home_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for [current_user, @post] do |p| %>
  <%= p.label :title %> <br>
  <%= p.text_field :title %>
  <br>
  <%= p.label :body %> <br>
  <%= p.text_area :body %>
  <br>
  <%= p.submit "Create Post" %>
<% end %>

<%= link_to "Back", user_posts_path %>

app/views/posts/show.html.erb
<h1>Post Show</h1>

<%= @post.title %> <br>
<%= @post.body %>

<hr>

<%= link_to "Back", user_posts_path %>

app/views/users/index.html.erb
<h1>Index</h1>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.full_messages %>
  <% else %>
    <h1>Welcome</h1>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email%> <br>
  <%= f.text_field :email %>
<br>
  <%= f.label :password %> <br>
  <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation%> <br>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign Up" %>
<% end %>